#pragma once
typedef struct AttractOamInfo {
  int8 x, y;
  uint8 c, f, e;
} AttractOamInfo;


extern const uint16 kMapMode_Zooms1[240];
extern const uint16 kMapMode_Zooms2[240];
void Attract_DrawSpriteSet2(const AttractOamInfo *p, int n);
void Attract_ZeldaPrison_Case0(void);
void Attract_ZeldaPrison_Case1(void);
void Attract_ZeldaPrison_DrawA(void);
void Attract_MaidenWarp_Case0(void);
void Attract_MaidenWarp_Case1(void);
void Attract_MaidenWarp_Case2(void);
void Attract_MaidenWarp_Case3(void);
void Attract_MaidenWarp_Case4(void);
void Dungeon_LoadAndDrawEntranceRoom(uint8 a);
void Dungeon_SaveAndLoadLoadAllPalettes(uint8 a, uint8 k);
void Module14_Attract(void);
void Attract_Fade(void);
void Attract_InitGraphics(void);
void Attract_FadeInStep(void);
void Attract_FadeInSequence(void);
void Attract_FadeOutSequence(void);
void Attract_LoadNewScene(void);
void AttractScene_PolkaDots(void);
void AttractScene_WorldMap(void);
void AttractScene_ThroneRoom(void);
void Attract_PrepFinish(void);
void Attract_PrepZeldaPrison(void);
void Attract_PrepMaidenWarp(void);
void AttractScene_EndOfStory(void);
void Death_Func31(void);
void Attract_EnactStory(void);
void AttractDramatize_PolkaDots(void);
void AttractDramatize_WorldMap(void);
void Attract_ThroneRoom(void);
void AttractDramatize_Prison(void);
void AttractDramatize_AgahnimAltar(void);
void Attract_SkipToFileSelect(void);
void Attract_BuildNextImageTileMap(void);
void Attract_ShowTimedTextMessage(void);
void Attract_ControlMapZoom(void);
void Attract_BuildBackgrounds(void);
void Attract_TriggerBGDMA(uint16 dstv);
void Attract_DrawPreloadedSprite(const uint8 *xp, const uint8 *yp, const uint8 *cp, const uint8 *fp, const uint8 *ep, int n);
void Attract_DrawZelda(void);
void Sprite_SimulateSoldier(int k, uint16 x, uint16 y, uint8 dir, uint8 flags, uint8 gfx);
