#pragma once

typedef struct IntroSpriteEnt {
  int8 x, y;
  uint8 charnum, flags;
  uint8 ext;
} IntroSpriteEnt;

void Intro_SetupScreen(void);
void Intro_LoadTextPointersAndPalettes(void);
void Credits_LoadScene_Overworld_PrepGFX(void);
void Credits_LoadScene_Overworld_Overlay(void);
void Credits_LoadScene_Overworld_LoadMap(void);
void Credits_OperateScrollingAndTileMap(void);
void Credits_LoadCoolBackground(void);
void Credits_LoadScene_Dungeon(void);
void Module18_GanonEmerges(void);
void Module19_TriforceRoom(void);
void Intro_InitializeBackgroundSettings(void);
void Polyhedral_InitializeThread(void);
void Module00_Intro(void);
void Intro_Init(void);
void Intro_Init_Continue(void);
void Intro_Clear1kbBlocksOfWRAM(void);
void Intro_InitializeMemory_darken(void);
void IntroZeldaFadein(void);
void Intro_FadeInBg(void);
void Intro_SwordComingDown(void);
void Intro_WaitPlayer(void);
void FadeMusicAndResetSRAMMirror(void);
void Intro_InitializeTriforcePolyThread(void);
void Intro_InitGfx_Helper(void);
void LoadTriforceSpritePalette(void);
void Intro_HandleAllTriforceAnimations(void);
void Scene_AnimateEverySprite(void);
void Intro_AnimateTriforce(void);
void Intro_RunStep(void);
void Intro_AnimOneObj(int k);
void Intro_SpriteType_A_0(int k);
void Intro_SpriteType_B_0(int k);
void AnimateSceneSprite_DrawTriangle(int k);
void Intro_CopySpriteType4ToOam(int k);
void EXIT_0CCA90(int k);
void InitializeSceneSprite_Copyright(int k);
void AnimateSceneSprite_Copyright(int k);
void InitializeSceneSprite_Sparkle(int k);
void AnimateSceneSprite_Sparkle(int k);
void AnimateSceneSprite_AddObjectsToOamBuffer(int k, const IntroSpriteEnt *src, int num);
void AnimateSceneSprite_MoveTriangle(int k);
void TriforceRoom_PrepGFXSlotForPoly(void);
void Credits_InitializePolyhedral(void);
void AdvancePolyhedral(void);
void TriforceRoom_HandlePoly(void);
void Credits_AnimateTheTriangles(void);
void InitializeSceneSprite_TriforceRoomTriangle(int k);
void Intro_SpriteType_B_456(int k);
void AnimateTriforceRoomTriangle_HandleContracting(int k);
void InitializeSceneSprite_CreditsTriangle(int k);
void AnimateSceneSprite_CreditsTriangle(int k);
void Intro_DisplayLogo(void);
void Intro_SetupSwordAndIntroFlash(void);
void Intro_PeriodicSwordAndIntroFlash(void);
void Module1A_Credits(void);
void Credits_LoadNextScene_Overworld(void);
void Credits_LoadNextScene_Dungeon(void);
void Credits_PrepAndLoadSprites(void);
void Credits_ScrollScene_Overworld(void);
void Credits_ScrollScene_Dungeon(void);
void Credits_HandleSceneFade(void);
void Credits_SpriteDraw_DrawShadow(int k);
void EndSequence_DrawShadow2(int k);
void Ending_Func2(int k, uint8 ain);
void Credits_SpriteDraw_ActivateAndRunSprite(int k, uint8 a);
void Credits_SpriteDraw_PreexistingSpriteDraw(int k, uint8 a);
void Credits_SpriteDraw_Single(int k, uint8 a, uint8 j);
void Credits_SpriteDraw_SetShadowProp(int k, uint8 a);
void Credits_SpriteDraw_AddSparkle(int j_count, uint8 xb, uint8 yb);
void Credits_SpriteDraw_WalkLinkAwayFromPedestal(int k);
void Credits_SpriteDraw_MoveSquirrel(int k);
void Credits_SpriteDraw_CirclingBirds(int k);
void Credits_HandleCameraScrollControl(void);
void EndSequence_32(void);
void Credits_FadeOutFixedCol(void);
void Credits_FadeColorAndBeginAnimating(void);
void Credits_AddNextAttribution(void);
void Credits_AddEndingSequenceText(void);
void Credits_BrightenTriangles(void);
void Credits_StopCreditsScroll(void);
void Credits_FadeAndDisperseTriangles(void);
void Credits_FadeInTheEnd(void);
void Credits_HangForever(void);
void CrystalCutscene_InitializePolyhedral(void);
