#pragma once
#include "types.h"

const uint8 *GetDungmapFloorLayout(void);
uint8 GetOtherDungmapInfo(int count);
void DungMap_4(void);
void Module_Messaging_6(void);
void OverworldMap_SetupHdma(void);
const uint8 *GetLightOverworldTilemap(void);
void SaveGameFile(void);
void TransferMode7Characters(void);
void Module0E_Interface(void);
void Module_Messaging_0(void);
void Module0E_05_DesertPrayer(void);
void Module0E_04_RedPotion(void);
void Module0E_08_GreenPotion(void);
void Module0E_09_BluePotion(void);
void Module0E_0B_SaveMenu(void);
void Module1B_SpawnSelect(void);
void CleanUpAndPrepDesertPrayerHDMA(void);
void DesertPrayer_InitializeIrisHDMA(void);
void DesertPrayer_BuildIrisHDMATable(void);
Pair16U DesertHDMA_CalculateIrisShapeLine(void);
void Animate_GAMEOVER_Letters(void);
void GameOverText_SweepLeft(void);
void GameOverText_UnfurlRight(void);
void Module12_GameOver(void);
void GameOver_AdvanceImmediately(void);
void Death_Func1(void);
void GameOver_DelayBeforeIris(void);
void GameOver_IrisWipe(void);
void GameOver_SplatAndFade(void);
void Death_Func6(void);
void Death_Func4(void);
void Animate_GAMEOVER_Letters_bounce(void);
void GameOver_Finalize_GAMEOVR(void);
void GameOver_SaveAndOrContinue(void);
void Death_Func15(bool count_as_death);
void GameOver_AnimateChoiceFairy(void);
void GameOver_InitializeRevivalFairy(void);
void RevivalFairy_Main_bounce(void);
void GameOver_RiseALittle(void);
void GameOver_Restore0D(void);
void GameOver_Restore0E(void);
void GameOver_ResituateLink(void);
void Module0E_0A_FluteMenu(void);
void FluteMenu_HandleSelection(void);
void FluteMenu_LoadSelectedScreen(void);
void Overworld_LoadOverlayAndMap(void);
void FluteMenu_FadeInAndQuack(void);
void BirdTravel_Finish_Doit(void);
void Messaging_OverworldMap(void);
void WorldMap_FadeOut(void);
void WorldMap_LoadLightWorldMap(void);
void WorldMap_LoadDarkWorldMap(void);
void WorldMap_LoadSpriteGFX(void);
void WorldMap_Brighten(void);
void WorldMap_PlayerControl(void);
void WorldMap_RestoreGraphics(void);
void Attract_SetUpConclusionHDMA(void);
void WorldMap_ExitMap(void);
void WorldMap_SetUpHDMA(void);
void WorldMap_FillTilemapWithEF(void);
void WorldMap_HandleSprites(void);
bool OverworldMap_CheckForPendant(int k);
bool OverworldMap_CheckForCrystal(int k);
void Module0E_03_DungeonMap(void);
void Module0E_03_01_DrawMap(void);
void Module0E_03_01_00_PrepMapGraphics(void);
void Module0E_03_01_01_DrawLEVEL(void);
void Module0E_03_01_02_DrawFloorsBackdrop(void);
void DungeonMap_BuildFloorListBoxes(uint8 t5, uint16 r14);
void Module0E_03_01_03_DrawRooms(void);
void DungeonMap_DrawBorderForRooms(uint16 pd, uint16 mask);
void DungeonMap_DrawFloorNumbersByRoom(uint16 pd, uint16 r8);
void DungeonMap_DrawDungeonLayout(int pd);
void DungeonMap_DrawSingleRowOfRooms(int i, int arg_x);
void DungeonMap_DrawRoomMarkers(void);
void DungeonMap_HandleInputAndSprites(void);
void DungeonMap_HandleInput(void);
void DungeonMap_HandleMovementInput(void);
void DungeonMap_HandleFloorSelect(void);
void DungeonMap_ScrollFloors(void);
void DungeonMap_DrawSprites(void);
void DungeonMap_DrawLinkPointing(int spr_pos, uint8 r2, uint8 r3);
int DungeonMap_DrawBlinkingIndicator(int spr_pos);
int DungeonMap_DrawLocationMarker(int spr_pos, uint16 r14);
int DungeonMap_DrawFloorNumberObjects(int spr_pos);
void DungeonMap_DrawFloorBlinker(void);
int DungeonMap_DrawBossIcon(int spr_pos);
int DungeonMap_DrawBossIconByFloor(int spr_pos);
void DungeonMap_RecoverGFX(void);
void ToggleStarTilesAndAdvance(void);
void Death_InitializeGameOverLetters(void);
void CopySaveToWRAM(void);
void RenderText(void);
void RenderText_PostDeathSaveOptions(void);
void Text_Initialize(void);
void Text_Initialize_initModuleStateLoop(void);
void Text_InitVwfState(void);
void Text_LoadCharacterBuffer(void);
uint8 *Text_WritePlayerName(uint8 *p);
uint8 Text_FilterPlayerNameCharacters(uint8 a);
void Text_Render(void);
void RenderText_Draw_Border(void);
void RenderText_Draw_BorderIncremental(void);
void RenderText_Draw_CharacterTilemap(void);
void RenderText_Draw_MessageCharacters(void);
void RenderText_Draw_Finish(void);
void VWF_RenderSingle(int);
void RenderText_Draw_Choose2LowOr3(void);
void RenderText_Draw_ChooseItem(void);
void RenderText_FindYItem_Previous(void);
void RenderText_FindYItem_Next(void);
void RenderText_DrawSelectedYItem(void);
void RenderText_Draw_Choose2HiOr3(void);
void RenderText_Draw_Choose3(void);
void RenderText_Draw_Choose1Or2(void);
bool RenderText_Draw_Scroll(void);
void RenderText_SetDefaultWindowPosition(void);
void RenderText_DrawBorderInitialize(void);
uint16 *RenderText_DrawBorderRow(uint16 *d, int y);
void Text_BuildCharacterTilemap(void);
void RenderText_Refresh(void);
void Text_GenerateMessagePointers(void);
void DungMap_LightenUpMap(void);
void DungMap_Backup(void);
void DungMap_FadeMapToBlack(void);
void DungMap_RestoreOld(void);
void Death_PlayerSwoon(void);
void Death_PrepFaint(void);
void DisplaySelectMenu(void);
bool DidPressButtonForMap(void);
