#pragma once


bool Intro_CheckCksum(const uint8 *s);
uint16 *SelectFile_Func1(void);
void SelectFile_Func5_DrawOams(int k);
void SelectFile_Func6_DrawOams2(int k);
void SelectFile_Func17(int k);
void SelectFile_Func16(void);
void Module_NamePlayer_1(void);
void Module_NamePlayer_2(void);
void Intro_FixCksum(uint8 *s);
void LoadFileSelectGraphics(void);
void Intro_ValidateSram(void);
void Module01_FileSelect(void);
void Module_SelectFile_0(void);
void FileSelect_ReInitSaveFlagsAndEraseTriforce(void);
void FileSelect_EraseTriforce(void);
void Module_EraseFile_1(void);
void FileSelect_TriggerStripesAndAdvance(void);
void FileSelect_TriggerNameStripesAndAdvance(void);
void FileSelect_Main(void);
void Module02_CopyFile(void);
void Module_CopyFile_2(void);
void CopyFile_ChooseSelection(void);
void CopyFile_ChooseTarget(void);
void CopyFile_ConfirmSelection(void);
void FilePicker_DeleteHeaderStripe(void);
void CopyFile_SelectionAndBlinker(void);
void ReturnToFileSelect(void);
void CopyFile_TargetSelectionAndBlink(void);
void CopyFile_HandleConfirmation(void);
void Module03_KILLFile(void);
void KILLFile_SetUp(void);
void KILLFile_HandleSelection(void);
void KILLFile_HandleConfirmation(void);
void KILLFile_ChooseTarget(void);
void FileSelect_DrawFairy(uint8 x, uint8 y);
void Module04_NameFile(void);
void NameFile_EraseSave(void);
void NameFile_DoTheNaming(void);
void NameFile_CheckForScrollInputX(void);
void NameFile_CheckForScrollInputY(void);
void NameFile_DrawSelectedCharacter(int k, uint16 chr);
